### ISSUE TITLE
Optimization is not working in Stage env.

### ISSUE THREAD

**Issue by KatrinaJewel** [rtercias/foreign-field#348]

**Comment by rtercias** [comment]
The error is intentional and is caused by a third party CORS proxy (https://cors-anywhere.herokuapp.com/corsdemo)

When not in production mode, we need a proxy to access the optimize API due to restrictive CORS policy. 

1. Go to this link: https://cors-anywhere.herokuapp.com/corsdemo 
2. Request the proxy server to be enabled 

The optimize API should then work.
